"""Typed blocking Python client for the TrenchBroom HTTP control API."""

from .client import Document, TrenchBroomClient
from .edit import EditBatch, Ref
from .errors import ApiError, ConnectionFailed, EditFailed, TrenchBroomError
from .types import (
    Bounds,
    BrushFaceInfo,
    DocumentInfo,
    EntityClass,
    FaceSel,
    Handle,
    HistoryResult,
    LayerInfo,
    MaterialCollection,
    NodeDetail,
    NodeRef,
    NodeSummary,
    NodeType,
    OpResult,
    RayHit,
    Selection,
    Vec2,
    Vec3,
    VecLike,
)

__all__ = [
    "TrenchBroomClient",
    "Document",
    "EditBatch",
    "Ref",
    "TrenchBroomError",
    "ConnectionFailed",
    "ApiError",
    "EditFailed",
    "Bounds",
    "BrushFaceInfo",
    "DocumentInfo",
    "EntityClass",
    "FaceSel",
    "Handle",
    "HistoryResult",
    "LayerInfo",
    "MaterialCollection",
    "NodeDetail",
    "NodeRef",
    "NodeSummary",
    "NodeType",
    "OpResult",
    "RayHit",
    "Selection",
    "Vec2",
    "Vec3",
    "VecLike",
]
